name: API Documentation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup PDM
        run: python -m pip install pdm 'requests<2.30.0'

      - name: Install dependencies
        run: pdm install --dev

      - name: Build documentation
        run: pdm run pdoc vi -o ./public -e vi=https://github.com/m-rots/violet/blob/main/vi/ -t templates

      - name: Publish to Pages
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish public --project-name=violet-api
